//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GunlukKiralikIlanlar
    {
        public int gunlukkiralikilanlarID { get; set; }
        public int ilanbilgileriID { get; set; }
    }
}
