//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanBilgileri
    {
        public int ilanbilgileriID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string Fiyat { get; set; }
        public string YatakSayisi { get; set; }
        public string BanyoSayisi { get; set; }
        public string Metrekare { get; set; }
        public string Resim { get; set; }
    }
}
