//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakSitesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanTipleri
    {
        public int ilantipleriID { get; set; }
        public bool DaireMi { get; set; }
        public bool RezidansMı { get; set; }
        public bool VillaMı { get; set; }
        public bool YazlikMi { get; set; }
        public bool DukkanYadaMagazaMı { get; set; }
        public bool OfisMi { get; set; }
        public bool TarlaMı { get; set; }
        public bool ZeytinlikMi { get; set; }
        public bool DevremülkMü { get; set; }
        public bool OtelMi { get; set; }
    }
}
