//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakSitesi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmlakSitesiDBEntities : DbContext
    {
        public EmlakSitesiDBEntities()
            : base("name=EmlakSitesiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deneme> Deneme { get; set; }
        public virtual DbSet<GunlukKiralikIlanlar> GunlukKiralikIlanlar { get; set; }
        public virtual DbSet<IlanBilgileri> IlanBilgileri { get; set; }
        public virtual DbSet<IlanTipleri> IlanTipleri { get; set; }
        public virtual DbSet<KiralikIlanlar> KiralikIlanlar { get; set; }
        public virtual DbSet<SatilikIlanlar> SatilikIlanlar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
    }
}
